### ISSUE TITLE
it doesn't work on debian 9

### ISSUE THREAD

**Issue by almoondsllc** [Crypto-Loot/cryptoloot-cli#1]
I followed all docs but i get this:

root@debian9:~/cryptoloot-cli-master/bin# nodejs crypto-loot xxxxxxxxxmykeyxxxxxxxxxxx

module.js:515
    throw err;
    ^

Error: Cannot find module 'accepts'
    at Function.Module._resolveFilename (module.js:513:15)
    at Function.Module._load (module.js:463:25)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/cryptoloot-cli-master/node_modules/express/lib/request.js:16:15)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)

**Comment by Crypto-Loot** [comment]
`npm install accepts`

Should do the trick

**Comment by almoondsllc** [comment]
it works now! thank you!

**Comment by almoondsllc** [comment]
So after npm install accept i did again npm install, launched with nodejs crypto-loot  xxxxmytoken and it worked now when I lunch I get:
Initializing...
An error occured Unhandled "error" event. ([object Object])

**Comment by daogster** [comment]
Did you ever resolve this? I am having the same issue

**Comment by almoondsllc** [comment]
Honestly I "fixed" reinstalling everything so I can't see I solved.

**Comment by daogster** [comment]
@almoondsllc lol super late but coin-imp accomplished this beautifully and with a lower dev fee
